variable_names: ["FLAG_OWN_CAR",
                 "FLAG_OWN_REALTY",
                 "CNT_CHILDREN",
                 "AMT_INCOME_TOTAL",
                 "NAME_INCOME_TYPE",
                 "NAME_EDUCATION_TYPE",
                 "NAME_FAMILY_STATUS",
                 "NAME_HOUSING_TYPE",
                 "DAYS_BIRTH",
                 "DAYS_EMPLOYED",
                 "FLAG_WORK_PHONE",
                 "FLAG_PHONE",
                 "FLAG_EMAIL",
                 "OCCUPATION_TYPE"]

features_names: ['FLAG_OWN_CAR',
                 'FLAG_OWN_REALTY',
                 'NAME_INCOME_TYPE',
                 'NAME_EDUCATION_TYPE',
                 'NAME_FAMILY_STATUS',
                 'NAME_HOUSING_TYPE',
                 'OCCUPATION_TYPE',
                 'FLAG_WORK_PHONE',
                 'FLAG_PHONE',
                 'FLAG_EMAIL',
                 'AGE',
                 'CNT_CHILDREN',
                 'AMT_INCOME_TOTAL',
                 'WORK_YEARS']

float_names: ['AGE',
              'CNT_CHILDREN',
              'AMT_INCOME_TOTAL',
              'WORK_YEARS']

categorical_names: ['FLAG_OWN_CAR',
                    'FLAG_OWN_REALTY',
                    'NAME_INCOME_TYPE',
                    'NAME_EDUCATION_TYPE',
                    'NAME_FAMILY_STATUS',
                    'NAME_HOUSING_TYPE',
                    'OCCUPATION_TYPE',
                    'FLAG_WORK_PHONE',
                    'FLAG_PHONE',
                    'FLAG_EMAIL']
